name: event
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.2.0
  shared_preferences: ^2.3.3
  provider: ^6.0.0
  dio: ^5.1.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Ensure Material Icons font is included
  uses-material-design: true

  # Add assets to your application
  assets:
    - assets/images/
